### ISSUE TITLE
Brave throws CORS error on load of basic example

### ISSUE THREAD

**Issue by JamesMilnerUK** [JamesMilnerUK/THREEAR#10]
Looks like Brave behaves slightly differently then Chrome in some respect to Canvas data. Would be good to figure out what's going on there.

![screenshot_20190221_200247](https://user-images.githubusercontent.com/8822075/53198208-b9bd9a00-3613-11e9-81f4-4f286177fef2.png)

**Comment by commentatorboy** [comment]
Have you tried to disable their shield?
Also it might also be because of the url in localhost is not https.

**Comment by JamesMilnerUK** [comment]
@commentatorboy that is plausible, I'll test this again when I get some time. Thanks for your input!

**Comment by JamesMilnerUK** [comment]
@commentatorboy you were right, disabling Shields fixed this issue.

Going to close. Might be worth updating the README to reference this issue at some point.
