### ISSUE TITLE
Webpack importing library not working... works with Parcel

### ISSUE THREAD

**Issue by gschian0** [JamesMilnerUK/THREEAR#121]
using webpack I get this readout in terminal... when running the basic example... Request Header file too large... 
`[WDS] Live Reloading enabled.
THREEAR.js:1 Allocated videoFrameSize 1228800
THREEAR.js:1 Pattern detection mode set to 1.
THREEAR.js:1 Pattern ratio size set to 0.500000.
script.js:166 i {parameters: {…}, markers: {…}, smoothMatrices: Array(0), arController: e, _updatedAt: null, …}
THREEAR.js:1 GET http://10.0.0.140:8080/234%20235%20240%20233%20240%20234%20240%20235%20240%20237%20240%20238%20240%20240%20240%20232%20229%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20228%20227%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20239%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20236%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20234%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20236%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20231%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20229%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20225%20149%20240%20240%20186%20216%20225%20174%20240%20240%20240%20237%20238%20240%20240%20240%20150%20107%20238%20231%20%2075%20208%20115%20147%20238%20228%20223%20226%20237%20180%20226%20240%20150%20%2062%20181%20213%20%2062%20187%20113%20169%20197%20%2072%20%2029%20237%20120%20%2050%20%2053%20207%20149%20%2063%20%2047%20%2078%20%2053%20184%20113%20101%20142%20%20%205%20150%20150%20%2045%20217%20186%20%2083%20121%20%2084%20220%20222%20%2058%20180%20121%20%2092%20128%20109%20237%20124%20155%20232%20161%20%2064%20149%20%2071%20240%20240%20%2076%20210%20%2098%20109%20122%20108%20240%20129%20%2051%20119%20161%20155%20149%20186%20240%20240%20%2098%20219%20135%20152%20207%20191%20236%20227%20152%20%2077%20175%20209%20235%20235%20240%20233%20240%20234%20240%20235%20240%20236%20240%20238%20240%20240%20240%20240%20229%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20227%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20236%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20234%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20236%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20232%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20229%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20225%20156%20240%20240%20186%20216%20225%20186%20240%20240%20240%20240%20240%20240%20240%20240%20150%20117%20240%20231%20%2072%20206%20115%20162%20240%20232%20223%20237%20240%20180%20226%20240%20150%20%2074%20187%20213%20%2051%20184%20103%20168%20197%20%2078%20%2029%20237%20120%20%2050%20%2053%20216%20144%20%2077%20%2051%20%2074%20%2061%20184%20106%20101%20142%20%20%205%20150%20152%20%2052%20217%20186%20%2085%20117%20%2089%20219%20219%20%2065%20184%20121%20%2092%20128%20100%20236%20125%20156%20240%20170%20%2073%20148%20%2071%20240%20240%20%2076%20210%20109%20109%20121%20%2099%20240%20137%20%2051%20120%20166%20164%20140%20186%20240%20240%20%2098%20220%20150%20156%20207%20192%20236%20230%20152%20%2077%20176%20212%20234%20235%20240%20233%20240%20234%20240%20235%20240%20236%20240%20238%20240%20240%20240%20233%20229%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20239%20227%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20234%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20232%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20235%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20232%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20228%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20225%20156%20240%20240%20182%20212%20225%20180%20240%20240%20240%20240%20240%20240%20240%20240%20150%20116%20238%20228%20%2066%20205%20115%20151%20238%20236%20225%20240%20240%20180%20226%20240%20156%20%2084%20186%20211%20%2047%20184%20109%20170%20200%20%2092%20%2030%20240%20120%20%2050%20%2053%20216%20147%20%2083%20%2051%20%2073%20%2050%20184%20106%20110%20148%20%2017%20151%20150%20%2045%20217%20186%20%2085%20127%20%2098%20219%20219%20%2058%20179%20109%20101%20128%20107%20237%20125%20155%20240%20163%20%2072%20155%20%2086%20240%20240%20%2076%20201%20%2085%20108%20121%20%2095%20232%20137%20%2051%20118%20153%20155%20149%20189%20240%20240%20%2098%20220%20141%20154%20206%20178%20235%20230%20152%20%2077%20175%20209%20232%20228%20239%20240%20240%20240%20240%20240%20240%20240%20240%20207%20%2083%20%2064%20155%20209%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20226%20%2053%20186%20161%20161%20175%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20180%20%2050%20217%20232%20119%20%2077%20240%20240%20240%20240%20240%20240%20240%20240%20240%20238%20237%20120%20%2045%20155%20%2051%20152%20238%20240%20240%20240%20240%20240%20240%20240%20240%20237%20226%20237%20150%20124%20129%20227%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20223%20%2029%20150%20237%20240%20236%20237%20240%20240%20240%20240%20240%20240%20240%20240%20240%20228%20%2072%20%20%205%20109%20108%20191%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20238%20197%20142%20128%20122%20207%20235%20240%20240%20240%20240%20240%20240%20240%20240%20174%20147%20169%20101%20%2092%20109%20152%20240%20240%20240%20240%20240%20240%20240%20240%20240%20225%20115%20113%20113%20121%20%2098%20135%20234%20240%20240%20240%20240%20240%20240%20240%20240%20216%20208%20187%20184%20180%20210%20219%20240%20240%20240%20240%20240%20240%20240%20240%20240%20186%20%2075%20%2062%20%2053%20%2058%20%2076%20%2098%20233%20240%20240%20240%20240%20240%20240%20240%20240%20240%20231%20213%20%2078%20222%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20238%20181%20%2047%20220%20240%20240%20235%20240%20240%20240%20240%20240%20240%20240%20240%20149%20107%20%2062%20%2063%20%2084%20%2071%20186%20234%20229%20227%20240%20236%20234%20236%20231%20229%20225%20150%20150%20149%20121%20149%20149%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20216%20%2085%20%2073%20164%20212%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20226%20%2053%20186%20170%20166%20176%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20180%20%2050%20217%20240%20120%20%2077%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20120%20%2052%20156%20%2051%20152%20238%20240%20240%20240%20240%20240%20240%20240%20240%20240%20237%20237%20152%20125%20137%20230%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20223%20%2029%20150%20236%20240%20236%20236%20240%20240%20240%20240%20240%20240%20240%20240%20240%20232%20%2078%20%20%205%20100%20%2099%20192%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20197%20142%20128%20121%20207%20235%20240%20240%20240%20240%20240%20240%20240%20240%20186%20162%20168%20101%20%2092%20109%20156%20240%20240%20240%20240%20240%20240%20240%20240%20240%20225%20115%20103%20106%20121%20109%20150%20234%20240%20240%20240%20240%20240%20240%20240%20240%20216%20206%20184%20184%20184%20210%20220%20240%20240%20240%20240%20240%20240%20240%20240%20240%20186%20%2072%20%2051%20%2061%20%2065%20%2076%20%2098%20233%20240%20240%20240%20240%20240%20240%20240%20240%20240%20231%20213%20%2074%20219%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20187%20%2051%20219%20240%20240%20235%20240%20240%20240%20240%20240%20240%20240%20240%20156%20117%20%2074%20%2077%20%2089%20%2071%20186%20235%20229%20227%20240%20236%20234%20236%20232%20229%20225%20150%20150%20144%20117%20148%20140%20233%20239%20240%20240%20240%20240%20240%20240%20240%20240%20240%20216%20%2085%20%2072%20155%20209%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20226%20%2053%20186%20163%20153%20175%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20180%20%2050%20217%20240%20118%20%2077%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20120%20%2045%20155%20%2051%20152%20238%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20150%20125%20137%20230%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20225%20%2030%20151%20237%20232%20235%20236%20240%20240%20240%20240%20240%20240%20240%20240%20240%20236%20%2092%20%2017%20107%20%2095%20178%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20238%20200%20148%20128%20121%20206%20235%20240%20240%20240%20240%20240%20240%20240%20240%20180%20151%20170%20110%20101%20108%20154%20240%20240%20240%20240%20240%20240%20240%20240%20240%20225%20115%20109%20106%20109%20%2085%20141%20234%20240%20240%20240%20240%20240%20240%20240%20240%20212%20205%20184%20184%20179%20201%20220%20240%20240%20240%20240%20240%20240%20240%20240%20240%20182%20%2066%20%2047%20%2050%20%2058%20%2076%20%2098%20233%20240%20240%20240%20240%20240%20240%20240%20240%20240%20228%20211%20%2073%20219%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20238%20186%20%2051%20219%20240%20240%20235%20240%20240%20240%20240%20240%20240%20240%20240%20156%20116%20%2084%20%2083%20%2098%20%2086%20189%20234%20229%20227%20240%20234%20232%20235%20232%20228%20225%20150%20156%20147%20127%20155%20149%20209%20175%20%2077%20152%20227%20236%20191%20207%20152%20135%20219%20%2098%20240%20240%20186%20149%20155%20161%20119%20%2051%20129%20240%20108%20122%20109%20%2098%20210%20%2076%20240%20240%20%2071%20149%20%2064%20161%20232%20155%20124%20237%20109%20128%20%2092%20121%20180%20%2058%20222%20220%20%2084%20121%20%2083%20186%20217%20%2045%20150%20150%20%20%205%20142%20101%20113%20184%20%2053%20%2078%20%2047%20%2063%20149%20207%20%2053%20%2050%20120%20237%20%2029%20%2072%20197%20169%20113%20187%20%2062%20213%20181%20%2062%20150%20240%20226%20180%20237%20226%20223%20228%20238%20147%20115%20208%20%2075%20231%20238%20107%20150%20240%20240%20240%20238%20237%20240%20240%20240%20174%20225%20216%20186%20240%20240%20149%20225%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20229%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20231%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20236%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20234%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20236%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20239%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20227%20228%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20229%20232%20240%20240%20240%20238%20240%20237%20240%20235%20240%20234%20240%20233%20240%20235%20234%20212%20176%20%2077%20152%20230%20236%20192%20207%20156%20150%20220%20%2098%20240%20240%20186%20140%20164%20166%20120%20%2051%20137%20240%20%2099%20121%20109%20109%20210%20%2076%20240%20240%20%2071%20148%20%2073%20170%20240%20156%20125%20236%20100%20128%20%2092%20121%20184%20%2065%20219%20219%20%2089%20117%20%2085%20186%20217%20%2052%20152%20150%20%20%205%20142%20101%20106%20184%20%2061%20%2074%20%2051%20%2077%20144%20216%20%2053%20%2050%20120%20237%20%2029%20%2078%20197%20168%20103%20184%20%2051%20213%20187%20%2074%20150%20240%20226%20180%20240%20237%20223%20232%20240%20162%20115%20206%20%2072%20231%20240%20117%20150%20240%20240%20240%20240%20240%20240%20240%20240%20186%20225%20216%20186%20240%20240%20156%20225%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20229%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20232%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20236%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20234%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20236%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20227%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20229%20240%20240%20240%20240%20238%20240%20236%20240%20235%20240%20234%20240%20233%20240%20235%20235%20209%20175%20%2077%20152%20230%20235%20178%20206%20154%20141%20220%20%2098%20240%20240%20189%20149%20155%20153%20118%20%2051%20137%20232%20%2095%20121%20108%20%2085%20201%20%2076%20240%20240%20%2086%20155%20%2072%20163%20240%20155%20125%20237%20107%20128%20101%20109%20179%20%2058%20219%20219%20%2098%20127%20%2085%20186%20217%20%2045%20150%20151%20%2017%20148%20110%20106%20184%20%2050%20%2073%20%2051%20%2083%20147%20216%20%2053%20%2050%20120%20240%20%2030%20%2092%20200%20170%20109%20184%20%2047%20211%20186%20%2084%20156%20240%20226%20180%20240%20240%20225%20236%20238%20151%20115%20205%20%2066%20228%20238%20116%20150%20240%20240%20240%20240%20240%20240%20240%20240%20180%20225%20212%20182%20240%20240%20156%20225%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20228%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20232%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20235%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20232%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20234%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20227%20239%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20229%20233%20240%20240%20240%20238%20240%20236%20240%20235%20240%20234%20240%20233%20240%20235%20234%20149%20149%20121%20149%20150%20150%20225%20229%20231%20236%20234%20236%20240%20227%20229%20234%20186%20%2071%20%2084%20%2063%20%2062%20107%20149%20240%20240%20240%20240%20240%20240%20240%20240%20235%20240%20240%20220%20%2047%20181%20238%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20222%20%2078%20213%20231%20240%20240%20240%20240%20240%20240%20240%20240%20240%20233%20%2098%20%2076%20%2058%20%2053%20%2062%20%2075%20186%20240%20240%20240%20240%20240%20240%20240%20240%20240%20219%20210%20180%20184%20187%20208%20216%20240%20240%20240%20240%20240%20240%20240%20240%20234%20135%20%2098%20121%20113%20113%20115%20225%20240%20240%20240%20240%20240%20240%20240%20240%20240%20152%20109%20%2092%20101%20169%20147%20174%20240%20240%20240%20240%20240%20240%20240%20240%20235%20207%20122%20128%20142%20197%20238%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20191%20108%20109%20%20%205%20%2072%20228%20240%20240%20240%20240%20240%20240%20240%20240%20240%20237%20236%20240%20237%20150%20%2029%20223%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20227%20129%20124%20150%20237%20226%20237%20240%20240%20240%20240%20240%20240%20240%20240%20238%20152%20%2051%20155%20%2045%20120%20237%20238%20240%20240%20240%20240%20240%20240%20240%20240%20240%20%2077%20119%20232%20217%20%2050%20180%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20175%20161%20161%20186%20%2053%20226%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20209%20155%20%2064%20%2083%20207%20240%20240%20240%20240%20240%20240%20240%20240%20239%20228%20232%20140%20148%20117%20144%20150%20150%20225%20229%20232%20236%20234%20236%20240%20227%20229%20235%20186%20%2071%20%2089%20%2077%20%2074%20117%20156%20240%20240%20240%20240%20240%20240%20240%20240%20235%20240%20240%20219%20%2051%20187%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20219%20%2074%20213%20231%20240%20240%20240%20240%20240%20240%20240%20240%20240%20233%20%2098%20%2076%20%2065%20%2061%20%2051%20%2072%20186%20240%20240%20240%20240%20240%20240%20240%20240%20240%20220%20210%20184%20184%20184%20206%20216%20240%20240%20240%20240%20240%20240%20240%20240%20234%20150%20109%20121%20106%20103%20115%20225%20240%20240%20240%20240%20240%20240%20240%20240%20240%20156%20109%20%2092%20101%20168%20162%20186%20240%20240%20240%20240%20240%20240%20240%20240%20235%20207%20121%20128%20142%20197%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20192%20%2099%20100%20%20%205%20%2078%20232%20240%20240%20240%20240%20240%20240%20240%20240%20240%20236%20236%20240%20236%20150%20%2029%20223%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20230%20137%20125%20152%20237%20237%20240%20240%20240%20240%20240%20240%20240%20240%20240%20238%20152%20%2051%20156%20%2052%20120%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20%2077%20120%20240%20217%20%2050%20180%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20176%20166%20170%20186%20%2053%20226%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20212%20164%20%2073%20%2085%20216%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20149%20155%20127%20147%20156%20150%20225%20228%20232%20235%20232%20234%20240%20227%20229%20234%20189%20%2086%20%2098%20%2083%20%2084%20116%20156%20240%20240%20240%20240%20240%20240%20240%20240%20235%20240%20240%20219%20%2051%20186%20238%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20219%20%2073%20211%20228%20240%20240%20240%20240%20240%20240%20240%20240%20240%20233%20%2098%20%2076%20%2058%20%2050%20%2047%20%2066%20182%20240%20240%20240%20240%20240%20240%20240%20240%20240%20220%20201%20179%20184%20184%20205%20212%20240%20240%20240%20240%20240%20240%20240%20240%20234%20141%20%2085%20109%20106%20109%20115%20225%20240%20240%20240%20240%20240%20240%20240%20240%20240%20154%20108%20101%20110%20170%20151%20180%20240%20240%20240%20240%20240%20240%20240%20240%20235%20206%20121%20128%20148%20200%20238%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20178%20%2095%20107%20%2017%20%2092%20236%20240%20240%20240%20240%20240%20240%20240%20240%20240%20236%20235%20232%20237%20151%20%2030%20225%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20230%20137%20125%20150%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20238%20152%20%2051%20155%20%2045%20120%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20%2077%20118%20240%20217%20%2050%20180%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20175%20153%20163%20186%20%2053%20226%20240%20240%20240%20240%20240%20240%20240%20240%20240%20240%20209%20155%20%2072%20%2085%20216%20240%20240%20240%20240%20240%20240%20240%20240%20240%20239%20233 431 (Request Header Fields Too Large)
e.ajax @ THREEAR.js:1
e.addMarker @ THREEAR.js:1
e.loadMarker @ THREEAR.js:1
i.trackPatternMarker @ THREEAR.js:1
i.trackMarker @ THREEAR.js:1
(anonymous) @ script.js:189
Promise.then (async)
(anonymous) @ script.js:165
(anonymous) @ bundle.2edf0b3ebc5ddc023fd6.js:108697
(anonymous) @ bundle.2edf0b3ebc5ddc023fd6.js:108884
THREEAR.js:1 Pattern Data read error!!
THREEAR.js:1 loadMarker(): Error loading pattern file /marker_0.
THREEAR.js:1 ARToolKitJS(): Unable to set up AR marker.
THREEAR.js:1 Out of memory!!
THREEAR.js:1 Uncaught ExitStatus {name: "ExitStatus", message: "Program terminated with exit(1)", status: 1}`

**Comment by JamesLMilner** [comment]
This looks like a request issue with your backend as the request returned 431 https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/431

**Comment by JamesLMilner** [comment]
Also can you clarify if this is the same issue you are seeing here? https://github.com/JamesLMilner/THREEAR/issues/118 Would be good to just keep it to one issue if so

**Comment by gschian0** [comment]
I don't think it's the same issue, but I will look into it again.

**Comment by JamesLMilner** [comment]
I'm going to close this as there's been no follow up for a fair while.
