### ISSUE TITLE
Destroy options.

### ISSUE THREAD

**Issue by stephanedemotte** [JamesMilnerUK/THREEAR#42]
I use it with in a SPA.

Could be great to add the possibility to destroy the sources and controller .

Thanks !

**Comment by JamesMilnerUK** [comment]
Thanks for raising this issue. This is definitely on the to-do list, I think we just need to be careful to find all the listeners and references and remove them appropriately from memory. I am confident it's possible and not too much of a big task!

**Comment by JamesMilnerUK** [comment]
@stephanedemotte hope this solves your issue! Just about to release a new version `v1.0.0-alpha.2`
