### ISSUE TITLE
minConfidence not set in PatternMarker.ts

### ISSUE THREAD

**Issue by stephanedemotte** [JamesMilnerUK/THREEAR#43]
https://github.com/JamesMilnerUK/THREEAR/blob/799d17c/src/PatternMarker.ts#L22

`this.minConfidence = parameters.size || 0.6;`

Should be `this.minConfidence = parameters.minConfidence || 0.6;` ?

Thanks !

**Comment by JamesMilnerUK** [comment]
Yes, this is definitely an error on my part. I will fix it, unless you feel like raising a PR @stephanedemotte since you've figured out what's wrong? :)
