### ISSUE TITLE
Z-fighting bug

### ISSUE THREAD

**Issue by 0b01001101** [JamesMilnerUK/THREEAR#52]
Same bug as in Ar.js, solved it by myself see:
https://github.com/jeromeetienne/AR.js/issues/146#issuecomment-474017046

```javascript
THREEAR.initialize({ source: source }).then(controller => {
    // ...
    let m = camera.projectionMatrix;
    let far = 1000;
    let near = 0.1;

    m.elements[10] = -(far + near) / (far - near);
    m.elements[14] = -(2 * far * near) / (far - near);
    // ...
});
```

**Comment by JamesMilnerUK** [comment]
Thanks for posting your solution to that problem. I am not totally sure if this is something that could be fixed at the library level or if it's something that should be being applied in user land code with Three.js?

**Comment by 0b01001101** [comment]
Maybe you can set the default near plane of the camera to 0.1 or 0.01, I think it would be an better default value than 0.0001.

One possibility is my workaround or maybe use the setProjectionNearPlane in arjs.artoolkit.debug.js

**Comment by JamesMilnerUK** [comment]
@0b01001101 thanks for the advice. Do you happen to have a reproduceable model / example source code I can play with by any chance?

**Comment by 0b01001101** [comment]
Added it to: https://github.com/0b01001101/THREEAR/tree/zfighting
model/zfighting
examples/bug-zfighting.html

On line 75/76 in _bug-zfighting.html_ you can "enable/disable" the bug

**Comment by JamesMilnerUK** [comment]
@0b01001101 thanks so much! I will take a look

**Comment by JamesMilnerUK** [comment]
In theory this is fixed now, will release soon.
