### ISSUE TITLE
Out of Memory FirefoxMobile

### ISSUE THREAD

**Issue by 0b01001101** [JamesMilnerUK/THREEAR#63]
I get an out of memory exeption in FF Mobile on a Xiomi Mi8[MIUI10.2, Android] on all online examples
But Chrome Mobile works

![Err](https://user-images.githubusercontent.com/20306567/56324274-b6a3dd80-616e-11e9-934c-299814d83d2c.PNG)

**Comment by 0b01001101** [comment]
I made som experiments with basic-image-source [Becouse it is really simple, no webcam]

In Chrome: const. 263MB
![MemoryChrome](https://user-images.githubusercontent.com/20306567/56327735-15bc1f00-617c-11e9-93d5-125041dd0854.PNG)

In Firefox:
![MemoryFF](https://user-images.githubusercontent.com/20306567/56327751-2e2c3980-617c-11e9-9a54-44259c4f1815.PNG)

In Firefox without controller.update(source.domElement)
![MemoryFF2](https://user-images.githubusercontent.com/20306567/56327775-4734ea80-617c-11e9-80f5-08fb58512399.PNG)

So it is possible that there is a memory leak somewere in the controller.update function

**Comment by 0b01001101** [comment]
Seems like getImageData in ARToolKitController.ts#L1077 causes the memory leak

https://github.com/JamesMilnerUK/THREEAR/blob/63ea8ac0389e60f137148928710df246f9ad5f6e/src/artoolkit/ARToolKitController.ts#L1077

**Comment by 0b01001101** [comment]
Issue can be closed for now, we can't do much to solve it

**Comment by JamesMilnerUK** [comment]
Closing as it appears to be a browser level bug.
