### ISSUE TITLE
Exclude three.js from libary

### ISSUE THREAD

**Issue by 0b01001101** [JamesMilnerUK/THREEAR#67]
![threearThreejs](https://user-images.githubusercontent.com/20306567/56368484-d03d3780-61f7-11e9-9a15-0cc4028127e0.PNG)

Would be nice if we exclude three.js from threear, so both libarys could be imported independently. [What I need for an other project with a big webpack config]
Even the examples include both libs seperately

**Comment by JamesMilnerUK** [comment]
This has been remedied by #68. Thank you! @stephanedemotte this maybe helps with #61 a little too :)
