### ISSUE TITLE
Low quality rendering

### ISSUE THREAD

**Issue by rremigius** [JamesMilnerUK/THREEAR#75]
Hi, nice adaptation from AR.js! Great improvement to be able to run in a div, turn on/off, etc. More modular.

An issue I had with AR.js and still with this library, is that, using this library, the rendering of my objects becomes really low quality. I haven't been able to figure out how to tweak it.

This is the object in plain THREE.js:
![Screenshot from 2019-05-01 20-49-48](https://user-images.githubusercontent.com/1083451/57035759-17451700-6c53-11e9-87ac-99e16ec351eb.png)

and this is the same object in the scene/rendering setup from ThreeAR:
![Screenshot from 2019-05-01 20-45-20](https://user-images.githubusercontent.com/1083451/57035799-2e840480-6c53-11e9-8156-39ef3bbd00b6.png)

I use the setup code from the [Basic Example](https://jamesmilneruk.github.io/THREEAR/examples/basic.html)

I also noticed that, if I render using my own PerspectiveCamera with size of the container, the low quality rendering is resolved. But then, of course, the scaling, aspect ratio and positioning is off.

I can imagine it has something to do with rendering size, but I haven't figured it out yet. Any help or fix would be much appreciated!

**Comment by 0b01001101** [comment]
See https://github.com/JamesMilnerUK/THREEAR/issues/52

Hope it will be fixed in the libary soon https://github.com/JamesMilnerUK/THREEAR/pull/71

**Comment by rremigius** [comment]
Thanks a lot! That does the trick for now (https://github.com/JamesMilnerUK/THREEAR/issues/52)

**Comment by JamesMilnerUK** [comment]
@rremigius that is #71 is merged now, hope to release earlier next week (I'm away this weekend). Glad you're enjoying the library.

**Comment by rremigius** [comment]
Great! Thanks, have a good weekend!
