### ISSUE TITLE
Issue with the examples.

### ISSUE THREAD

**Issue by imokya** [JamesMilnerUK/THREEAR#87]
I use my android cellphone to test the examples. Only the basic.html works, for the others I got 'Uncaught ExistStatus' Exceptions.

**Comment by JamesMilnerUK** [comment]
Hi @imokya, thanks for your issue. Can you please let me know your browser version and paste the full stack trace below? Thanks.

**Comment by imokya** [comment]
I retested the basic-cutout example. it seemed to work fine. im sorry for that and thanks for the reply.
