### ISSUE TITLE
Lost markers are not always detected

### ISSUE THREAD

**Issue by floogulinc** [JamesMilnerUK/THREEAR#90]
Firstly, thank you for making this library. It is much easier to use and read, especially for an Angular project like what I'm working on.

We are having an issue with THREEAR where our barcode markers being reported as found long after they have been removed from the image. This happens when a single marker is being found and then the camera is moved off of it. The `lostTimeout` does not seem to change this behavior. 

I believe I have found the reason for this. In [`ARToolKitController.ts`](https://github.com/JamesMilnerUK/THREEAR/blob/master/src/artoolkit/ARToolKitController.ts) when a frame is processed, if ARToolKit detects no markers the for loop is never gone through so the `getMarker` event is not emitted and thus [the part of `handleMarkerDetection()`](https://github.com/JamesMilnerUK/THREEAR/blob/master/src/Controller.ts#L351) in [`Controller.ts`](https://github.com/JamesMilnerUK/THREEAR/blob/master/src/Controller.ts) that checks for lost markers isn't executed. This means that a marker will continue to be found until another marker or something that ARToolKit thinks is a marker at any level of certainty enters the frame.

The lost marker detection should probably be run on its own event that occurs once at the end of the [`process()` function](https://github.com/JamesMilnerUK/THREEAR/blob/master/src/artoolkit/ARToolKitController.ts#L134) each frame.

**Comment by JamesMilnerUK** [comment]
Hi @floogulinc I think I see what you're saying. Let me have a look at trying to get that fixed. Thanks!

**Comment by JamesMilnerUK** [comment]
@floogulinc if you get the chance can you post an example of the issue so I can reproduce?

**Comment by JamesMilnerUK** [comment]
I just released v1.0.0-alpha.5 which should fix this. Let me know if it does! @floogulinc

**Comment by floogulinc** [comment]
@JamesMilnerUK It appears to have fixed the issue. Thanks!
